apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: kube-system
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  version: 0.9.1
  targetNamespace: vault
  valuesContent: |-
    global:
      enabled: true
      tlsDisable: false
    server:
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca

      extraVolumes:
        - type: secret
          name: vault-server-tls # Matches the ${SECRET_NAME} from pre_install.sh
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
            tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
            tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
          }
          storage "file" {
            path = "/vault/data"
          }
      dataStorage:
        enabled: true
        size: 5Gi
        storageClass: longhorn
    ui:
      enabled: true
